### ISSUE TITLE
tabbed-admin not working with django 1.11

### ISSUE THREAD

**Issue by MathiasWedeken** [omji/django-tabbed-admin#16]
in django 1.11, using tabbed-admin causes an error when rendering the admin add view template. Error says "context must be a dict, not RequestContext".

**Comment by Gedzis** [comment]
👍  solution needed. @omji can you review and merge suggested solution?

**Comment by omji** [comment]
Hi,

All apologies for the long delay. This should be fixed with release 1.0.2
