### ISSUE TITLE
Dajngo admin form error notification message is hidden by div.

### ISSUE THREAD

**Issue by drgmrscb** [omji/django-tabbed-admin#19]
This occurs on a project which uses grappelli + gipsy + tabbed admin. Example in screen shot bellow.
![tabbed](https://user-images.githubusercontent.com/11584390/30739100-ee202f36-9f94-11e7-9228-c32410331936.png)

**Comment by omji** [comment]
Should be fixed in gipsy 2.10 https://pypi.python.org/pypi/django-gipsy/2.10
