### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by justinask7** [omji/django-tabbed-admin#23]
Tabbed admin isn't working with Django 2.0. Probably because TabbedAdmin uses django.forms.Media.add_css() and django.forms.Media.add_js() functions, which do not exist in Django 2.0. 

Question - are there any plans on making TabbedAdmin compatible with Django 2.0?

**Comment by Gedzis** [comment]
👍

**Comment by Gedzis** [comment]
@omji any timeline on this issue fix?

**Comment by ogtony** [comment]
Sent up a pull request to fix this issue. Let me know if you need me to do any other work or testing on it.
